=== LundOgBendsen/LB2748-adv-xml/examples/xsd/03/person.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema
        targetNamespace="http://lundogbendsen.dk/schemas/2021/08/03/Person"
        xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <element name="person">
        <complexType>
            <sequence>
                <element name="name">
                    <simpleType>
                        <restriction base="string">
                            <minLength value="2"/>
                            <maxLength value="40"/>
                        </restriction>
                    </simpleType>
                </element>

                <element name="licensePlate">
                    <simpleType>
                        <restriction base="string">
                            <pattern value="[A-Z]{2}\d{4}"/>
                        </restriction>
                    </simpleType>
                </element>
                <element name="hero">
                    <simpleType>
                        <restriction base="boolean">
                            <pattern value="true|false"/>
                        </restriction>
                    </simpleType>
                </element>
                <element name="netWorth">
                    <simpleType>
                        <restriction base="int">
                            <minInclusive value="-100"/>
                            <maxInclusive value="100"/>
                        </restriction>
                    </simpleType>
                </element>

                <element name="birthdate" type="date"/>
                <element name="massOnEarth" type="decimal"/>
                <element name="favouriteSmallPrime">
                    <simpleType>
                        <restriction base='integer'>
                            <enumeration value='2'/>
                            <enumeration value='3'/>
                            <enumeration value='5'/>
                            <enumeration value='7'/>
                        </restriction>
                    </simpleType>
                </element>
            </sequence>
        </complexType>
    </element>
    <simpleType name="ikkeNovEllerDec">
        <restriction base="gMonth">
            <maxExclusive value="9"/>
        </restriction>
    </simpleType>

</schema>

=== LundOgBendsen/LB2748-adv-xml/examples/xsd/03/luke.xml
<person xmlns="http://lundogbendsen.dk/schemas/2021/08/03/Person"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://lundogbendsen.dk/schemas/2021/08/02/Person ./person.xsd">
  <name>ab</name>
  <licensePlate>BB1223</licensePlate>
  <hero>true</hero>
  <netWorth>3</netWorth>
  <birthdate>2007-10-26</birthdate>
  <massOnEarth>1000.00</massOnEarth>
  <favouriteSmallPrime>2</favouriteSmallPrime>
</person>
