=== LundOgBendsen/LB2748-adv-xml/examples/xsd/05/text.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema
        targetNamespace="http://lundogbendsen.dk/schemas/2021/08/02/Text"
        xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
        xmlns:tns="http://lundogbendsen.dk/schemas/2021/08/02/Text">
    <element name="text" type="tns:textType"/>
    <complexType name="textType">
        <choice maxOccurs="unbounded">
            <element name="b" type="string"/> <!--bold, fed -->
            <element name="i" type="string"/> <!--italics, kursiv -->
            <element name="u" type="string"/> <!--underline, understreget -->
            <element name="p" type="string"/> <!--plain/paragraph, alm.tekst -->
        </choice>
    </complexType>
</schema>

=== LundOgBendsen/LB2748-adv-xml/examples/xsd/05/dagbog.xml
<text xmlns="http://lundogbendsen.dk/schemas/2021/08/02/Text"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://lundogbendsen.dk/schemas/2021/08/02/Text ./text.xsd">
  <b>Dagbog</b>
  <b>1-1-2020</b>
  <p>En glad dag</p>
  <p>Her er et digt:</p>
  <i>roser er røde</i>
  <i>violer er blå</i>
  <i>kærlighed...</i>
  <i>..er svær at få</i>
  <p>Lad mig understrege</p>
  <u>at dette er mit første digt!</u>
</text>
